package DayOne.Exception;

public class ArithmeticException {
    public static void main(String[] args) {

        try{
            int a =40/5;
        }catch (Exception e){
            System.out.println("Arithmetic Exception");
        }
    }
}
